name:                CakeFree-SDL2
version:             0.1.0.0
github:              "OmegaGreeNya/CakeFree-SDL2"
license:             BSD3
author:              "GreenCake (Nikolai)"
maintainer:          "megamancake@yandex.ru"
copyright:           "2022 GreenCake (Nikolai)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/OmegaGreeNya/CakeFree-SDL2#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- free
- hashable
- hashtables
- lens
- linear
- sdl2
- sdl2-image
- sdl2-ttf
- sdl2-mixer
- text
- ghc-prim
default-extensions:
- GADTs
- ExplicitForAll
- RankNTypes
- RecordWildCards
- OverloadedStrings
- TemplateHaskell
- MultiParamTypeClasses
- FunctionalDependencies
- TypeSynonymInstances
- FlexibleInstances



library:
  source-dirs: src

executables:
  CakeFree-SDL2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CakeFree-SDL2

tests:
  CakeFree-SDL2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CakeFree-SDL2
